base/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'base'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(authentication_form = LoginForm, template_name='base/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/logout.html'), name="logout"),
]

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>', views.details, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

trade_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from base.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('base.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from io import BytesIO
from PIL import Image

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(
        Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    thumbnail = models.ImageField(
        upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name='items', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

    def get_display_price(self):
        return self.price / 100

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/300x300.jpg'

    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'PNG', quality=85)

        thumbnail = File(thumb_io, name=image.name)
        return thumbnail

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return 'https://via.placeholder.com/240x240.jpg'

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full px-4 py-4 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image') 
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),  
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),    
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }), 
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),   
        }
    
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold') 
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),  
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),    
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }), 
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),   
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Category
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .forms import NewItemForm, EditItemForm

# Create your views here.

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id != 0:
        items = items.filter(category_id=category_id)
    
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })
def details(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    
    return render(request, 'item/details.html', {
        'item': item,
        'related_items': related_items,
    })

@login_required 
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save() 
            return redirect('item:detail', pk=item.pk)
    else:       
        form = NewItemForm()
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })
    
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    
    return redirect('dashboard:index')

@login_required 
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.pk)
    else:       
        form = EditItemForm(instance=item)
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })

item/templates/item/details.html
{% extends 'main.html' %}
{% load ratings %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}
    <div class="flex flex-row flex-wrap">
        <div class="w-1/2 ">
            <img src="{{ item.get_image }}" alt="{{ item.name }}" class="rounded-xl max-h-[80vh]">
        </div>

        <div class="w-1/2 p-6 bg-gray-900 rounded-xl text-center">
            <h1 class="mb-6 text-3xl text-white">{{ item.name }}</h1>

            <div class="flex flex-col">
                <div>
                    
                </div>
            </div>

            <p class="text-white "><strong>Price:</strong> {{ item.get_display_price }} lei</p>
            <p class="text-white "><strong>Seller:</strong> {{ item.created_by.username }}</p><br>

            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong>
                    {{ item.description }}
                </p>
            {% endif %}
            <div>
                <h2 class="text-gray-500">Rating:</h2>
                {% ratings item %}
            </div>

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!</p>
                    <a href="{% url 'item:edit' item.id %}"
                       class="inline-block mt-6 px-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition-all">Edit</a>
                    <a href="{% url 'item:delete' item.id %}"
                       class="inline-block mt-6 px-6 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700 transition-all">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'conversation:new' item.id %}"
                   class="inline-block mt-6 px-6 py-4 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact
                    Seller</a>

                <div>
                    <a
                            href="#"
                            class=""
                            hx-get="{% url 'add_to_cart' item.id %}"
                            hx-target="#menu-cart-button"
                            hx-swap="outerHTML"
                    >
                        Add to cart
                    </a>
                </div>
            {% endif %}

        </div>
    </div>
    <div class="">
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Related items</h2>

            <div class="flex flex-row justify-start align-items-center flex-wrap gap-6">
                {% for item in related_items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="w-[300px] h-[300px] rounded-t-xl"
                                 style="background-image: url('{{ item.image.url }}'); background-size: cover;">
                                {#                               <img src="{{item.get_thumbnail}}" alt="{{item.name}}" class="rounded-t-xl">#}
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.get_display_price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

item/templates/item/form.html
{% extends 'main.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1 class="mb-6 text-3xl">
    {{title}}
</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="space-y-4">
        {{form.as_p}}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>

{% endblock content %}

item/templates/item/items.html
{% extends 'main.html' %}

{% block title %}Items{% endblock title %}

{% block content %}
    <div class="flex flex-col lg:flex-row gap-5 bg-gray-200 p-6 rounded-xl">
        <div class="w-1/3">
            <form action="{% url 'item:items' %}" method="get">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}"
                       placeholder="Search...">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %}  bg-gray-300 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>
            <ul>
                <li><a href="{% url 'item:items' %}"
                       class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-lg text-white">Clear</a></li>
            </ul>
        </div>
        <div class="w-2/3">
            <div class="flex flex-row flex-wrap gap-6">
                {% for item in items %}
                    <div >
                        <a href="{% url 'item:detail' item.id %}" >
                            <div class="w-[300px] h-[300px] rounded-t-xl"
                                 style="background-image: url('{{ item.get_thumbnail }}'); background-size: cover;">
{#                                <img src="{{ item.get_thumbnail }}" alt="{{ image.name }}" class="rounded-t-xl">#}
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}