base/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'base'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(authentication_form = LoginForm, template_name='base/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/logout.html'), name="logout"),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),    
]   

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>', views.details, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

trade_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from base.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('base.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from item.models import Item
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)
    
    return render(request, 'dashboard/index.html', {
        'items': items,
    })
    

dashboard/templates/dashboard/index.html
{% extends 'main.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

    <div>
        <a href="{% url 'base:logout' %}">Logout</a>
    </div>



    <div>
        <a href="{% url 'base:login' %}">Login</a>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items</h2>

        <div class="flex flex-wrap justify-center items-center gap-6">
            {% for item in items %}
                <div class="">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="w-[450px] h-[450px] rounded-t-xl" style="background-image: url('{{ item.get_thumbnail }}'); background-size: cover;">
{#                            <img src="{{item.get_thumbnail}}" alt="{{item.name}}" class="rounded-t-xl">#}
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{item.price}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}