base/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'base'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(authentication_form = LoginForm, template_name='base/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/logout.html'), name="logout"),
]

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>', views.details, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

trade_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from base.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('base.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main.html
{% load static %}
{% load bootstrap_icons %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock title %} | Trade Point</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</head>

<body>
<nav class="py-6 px-6 flex flex-col space-y-12 lg:space-y-0 lg:flex-row lg:justify-around items-center text-white " id="navbar">
    <div class="flex gap-2 items-center">
        {#            {% bs_icon 'envelope-paper-heart-fill' size='1.5em' %}#}
        {% bs_icon 'shield-lock-fill' size='1em' %}
        <span class="text-2xl font-bold animate-pulse" style="color: #537FE7;"><a href="{% url 'base:index' %}">Trade Point</a></span>
        {#            {% bs_icon 'question-circle-fill' size='1em' %}#}
        {#            #}
        {#            {% bs_icon 'phone-fill' size='1em' %}#}
    </div>
    <div class="flex space-x-6 ">
        <div class="flex items-center space-x-2 hover:text-teal-500 hover:cursor-pointer hover:opacity-80">
            {% bs_icon 'person-fill' size='1.5em' %}
            {% if request.user.is_authenticated %}
            <span class="text-teal-500 font-bold text-xl">{{request.user.username}}</span>
            {% endif %}
        </div>
        <div class="flex items-center space-x-2 hover:text-teal-500 hover:cursor-pointer hover:opacity-80">
            {% bs_icon 'chat-left-fill' size='1.3em' %}
            <span class="text-lg font-bold"><a href="{% url 'conversation:inbox' %}">Messages</a></span>
        </div>
        <a href="{% url 'item:new' %}" class="trasition ease-in-out delay-150 duration-300 text-lg font-bold bg-gray-800 px-5 py-2
                rounded-lg flex gap-2 items-center hover:bg-gray-900 hover:-translate-y-110 hover:scale-110">
            {% bs_icon 'plus-lg' size='1.3em' extra_classes='animate-pulse' %}
            New trade
        </a>
    </div>
    <div>
        <div>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'base:signup' %}" class="p-3">Sign Up</a>
            {% else %}
            <div hx-get="{% url 'hx_menu_cart' %}" hx-trigger="update-menu-cart from:body" hx-swap="innerHTML" class="flex flex-row space-x-4">
                <div>
                    {% include 'cart/partials/menu_cart.html' %}
                </div>
                <div>
                    <a href="{% url 'base:logout' %}" class="p-2 bg-gray-800 rounded-xl font-bold text-lg hover:bg-gray-900 hover:text-xl transition-all">Log Out</a>
                </div>
            </div>
            {% endif %}
        </div>
        <!-- <div hx-get="{% url 'hx_menu_cart' %}" hx-trigger="update-menu-cart from:body" hx-swap="innerHTML">
            {% include 'cart/partials/menu_cart.html' %}
        </div> -->
    </div>
</nav>

<div class="px-6 py-6">
    {% block content %}{% endblock content %}
</div>

<footer class="py-6 px-6 flex flex-bewtween bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione ipsa
                itaque, fugiat maiores architecto officiis harum quisquam nisi numquam possimus veritatis voluptas
                laborum doloribus libero amet ipsum nostrum in molestiae.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'base:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
                </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
            </ul>
        </div>
    </footer>


<script src="https://unpkg.com/htmx.org@1.8.5"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js" integrity="sha512-f8mwTB+Bs8a5c46DEm7HQLcJuHMBaH/UFlcgyetMqqkvTcYg4g5VXsYR71b3qC82lZytjNYvBj2pf0VekA9/FQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    gsap.from('#navbar',{
        duration:0.4,
        opacity:0,
        y:200,
    });
</script>

{% block scripts %}

{% endblock %}

</body>

</html>